
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: ssh_public_key
  inputs:
    secureFile: 'id_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AZ-DEVOPS-K8S-TF/Configuration/Iaac/Azure/Kubernetes'
    commandOptions: '-var client_id=$(client_id) -var clent_secret=$(client_secret) -v ssh_public_key=$(ssh_public_key.id_rsa.pub)'
    backendType: 'azurerm'
    backendServiceArm: 'azserviceconnection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'shivaniaztfk8rg'
    backendAzureRmResourceGroupLocation: 'WestEurope'
    backendAzureRmStorageAccountName: 'shivaniaztfk8sa'
    backendAzureRmContainerName: 'shivaniaztfk8cn'
    backendAzureRmKey: 'az-tf-k8.tfstate'
    allowTelemetryCollection: true


- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AZ-DEVOPS-K8S-TF/Configuration/Iaac/Azure/Kubernetes'
    environmentServiceName: 'azserviceconnection'
    commandOptions: '-var client_id=$(client_id) -var clent_secret=$(client_secret) -v ssh_public_key=$(ssh_public_key.id_rsa.pub)'
    allowTelemetryCollection: true

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
